[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
day01-part1 = []
day01-part2 = []
day01 = ["day01-part1", "day01-part2"]
day02-part1 = []
day02-part2 = []
day02 = ["day02-part1", "day02-part2"]

[dependencies]
anyhow = "1.0.75"
regex = "1.10.2"
rstest = "0.18.2"
